[package]
name = "quizzo"
version = "0.1.0"
edition = "2018"
resolver = "2"

[dependencies]
itertools = "0.10"
serde_json = "1.0"
slab = "0.4"

[dependencies.hyper]
version = "0.14"
default-features = false
features = ["client", "http2"]

[dependencies."hyper-rustls"]
version = "0.22"
default-features = false
features = ["webpki-tokio"]

[dependencies.serde]
version = "1.0"
default-features = false
features = ["derive"]

[dependencies.serenity]
version = "0.10"
default-features = false
features = ["client", "gateway", "model", "rustls_backend", "unstable_discord_api"]

[dependencies.tokio]
version = "1.10"
default-features = false
features = ["rt", "sync", "time"]
