[package]
name = "quizzo"
version = "0.3.0"
edition = "2021"
resolver = "2"

[dependencies]
anyhow = "1"
dashmap = { version = "5.1", default-features = false }
twilight-model = { version = "0.9", default-features = false }

[dependencies.hyper]
version = "0.14"
default-features = false
features = ["client"]

[dependencies.hyper-trust-dns]
version = "0.3"
default-features = false
features = ["https-only", "rustls-http2", "rustls-native"]

[dependencies.serde]
version = "1"
default-features = false
features = ["derive"]

[dependencies.tokio]
version = "1"
default-features = false
features = ["sync"]

[dependencies.twilight-http]
version = "0.9"
default-features = false
features = ["decompression", "rustls-native-roots", "trust-dns"]
