[package]
name = "quizzo"
version = "0.2.0"
edition = "2018"
resolver = "2"

[dependencies.ring]
version = "0.16"
default-features = false

[dependencies.hex]
version = "0.4"
default-features = false
features = ["alloc"]

[dependencies.hyper]
version = "0.14"
default-features = false
features = ["server", "tcp", "http1"]

[dependencies.serde]
version = "1"
default-features = false

[dependencies.serde_json]
version = "1"
default-features = false
features = ["alloc"]

[dependencies.tokio]
version = "1.11"
default-features = false
features = ["rt"]
