[workspace]
members = [
    "crates/api",
    "crates/model",
    "crates/lobby",
]

[package]
name = "quizzo"
version = "0.4.4"
edition = "2021"

[dependencies]
anyhow = "1"
futures-util = { version = "0.3", default-features = false }
lobby = { path = "crates/lobby", package = "quizzo-lobby" }
ring = { version = "0.16", default-features = false }

[dependencies.hex]
version = "0.4"
default-features = false
features = ["std"]

[dependencies.hyper]
version = "0.14"
default-features = false
features = ["http1", "server"]

[dependencies.tokio]
version = "1.17"
default-features = false
features = ["rt-multi-thread", "parking_lot"]

[profile.release]
lto = true
