[package]
name = "quizzo"
version = "0.3.0"
edition = "2021"
resolver = "2"

[dependencies]
dashmap = { version = "5.1", default-features = false }
twilight-model = { version = "0.9", default-features = false }

[dependencies.hyper]
version = "0.14"
default-features = false
features = ["client"]

[dependencies.hyper-rustls]
version = "0.23"
default-features = false
features = ["native-tokio"]

[dependencies.serde]
version = "1"
default-features = false
features = ["derive"]

[dependencies.tokio]
version = "1"
default-features = false
features = ["sync"]

[dependencies.twilight-http]
version = "0.9"
default-features = false
features = ["decompression", "rustls-native-roots"]
