[package]
name = "quizzo"
version = "0.2.0"
edition = "2018"
resolver = "2"

[dependencies]
hyper-tls = "0.5"

[dependencies.ring]
version = "0.16"
default-features = false

[dependencies.hex]
version = "0.4"
default-features = false
features = ["alloc"]

[dependencies.hyper]
version = "0.14"
default-features = false
features = ["server", "client", "tcp", "http1"]

[dependencies.parking_lot]
version = "0.11"
default-features = false

[dependencies.slab]
version = "0.4"
default-features = false

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.serde_json]
version = "1"
default-features = false
features = ["alloc"]

[dependencies.tokio]
version = "1.11"
default-features = false
features = ["rt", "sync", "parking_lot"]
