[package]
name = "quizzo-api"
version = "0.6.0"
edition = "2021"

[dependencies]
dashmap = { version = "5.3", default-features = false }
db = { path = "../db", package = "quizzo-db" }
model = { path = "../model", package = "quizzo-model" }
parking_lot = "0.12"
rand_core = { version = "0.6", default-features = false }
ring = { version = "0.16", default-features = false }
serde_json = "1"
twilight-model = "0.13"

[dependencies.hex]
version = "0.4"
default-features = false
features = ["alloc"]

[dependencies.hyper]
version = "0.14"
default-features = false
features = ["client", "http1"]

[dependencies.hyper-trust-dns]
version = "0.4"
default-features = false
features = ["https-only", "rustls-http1", "rustls-native"]

[dependencies.tokio]
version = "1.20"
default-features = false
features = ["macros", "sync", "time"]

[dependencies.twilight-http]
version = "0.13"
default-features = false
features = ["decompression", "rustls-native-roots", "trust-dns"]
