[package]
name = "quizzo-api"
version = "0.4.4"
edition = "2021"

[dependencies]
db = { path = "../db", package = "quizzo-db" }
model = { path = "../model", package = "quizzo-model" }
hyper = { version = "0.14", default-features = false }
serde_json = "1"
