[package]
name = "quizzo-db"
version = "0.6.0"
edition = "2021"

[dependencies]
model = { path = "../model", package = "quizzo-model" }

[dependencies.tokio-postgres]
version = "0.7"
features = ["with-uuid-1"]

[dependencies.futures-util]
version = "0.3"
default-features = false
