[package]
name = "quizzo-db"
version = "0.6.0"
edition = "2021"

[dependencies]
model = { path = "../model", package = "quizzo-model" }
tokio-postgres = "0.7"

[dependencies.futures-util]
version = "0.3"
default-features = false
