[package]
name = "quizzo-db"
version = "0.6.0"
edition = "2021"

[dependencies]
model = { path = "../model", package = "quizzo-model" }
mongodb = "2.3"

[dependencies.hex]
version = "0.4"
default-features = false
features = ["alloc"]
