[package]
name = "quizzo-model"
version = "0.6.0"
edition = "2021"

[dependencies.uuid]
version = "1"
default-features = false
features = ["serde"]

[dependencies.serde]
version = "1"
default-features = false
features = ["derive"]
